name: CI to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - run: cd web & npm install -g yarn
      - run: cd web & yarn install --frozen-lockfile
      
      - name: Build
        run: cd web && yarn build

      - name: Generate deployment package
        run: cd web && zip -r deploy.zip .next package.json
