name: CI to AWS Elastic Beanstalk

on:
  push:
    branches: [staging]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: cd web && npm install -g yarn
      - run: cd web && yarn install --frozen-lockfile
      - run: cd web && yarn
      - name: Build
        run: cd web && yarn build

      - name: Generate deployment package
        run: cd web && zip -r deploy.zip . -x '*.git*' -x node_modules/\*

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: solas.ai staging site
          environment_name: Solasaistagingsite-env
          version_label: ${{ github.ref }}
          region: us-east-1
          deployment_package: web/deploy.zip
